version: "3.9"
services:
  api:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SomePassword123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nightmail.pfx
    volumes:
      - ./backend/conf.d/https:/https:ro
    depends_on: 
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    container_name: db
    ports:
      - "1433:1433"
  angular-ui:
    build: ./frontend
    ports:
      - '8080:80'
    depends_on:
      - api
    restart: always